cars = ['bmw', 'audi', 'toyota', 'subaro']
print(cars)
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
print("Here is the sorted list:")
print(sorted(cars))
print("Here is the original list:")
print(cars)
cars.reverse()
print(cars)
print(len(cars))