languages = ['python', 'c++', 'javascript']
print(f'I have {len(languages)} programming languages to learn and master')
print("------------------------------------------------------------")
print("This is the list in original order")
print(languages)
print("------------------------------------------------------------")
print("This is the list in it is sort")
languages.sort()
print(languages)
print("------------------------------------------------------------")
print("When reverse")
languages.reverse()
print(languages)
print("------------------------------------------------------------")
print("When sorted but can pull the original order")
print(sorted(languages))
print("------------------------------------------------------------")
print("Can still display the latest order before sorted")
print(languages)
print("------------------------------------------------------------")
print(f"Im learning {languages[0].title()} right now because its my priority.")
print(f"My alternative programming language is {languages[2].title()} so if i rearrange the order is should like this.")
languages[0] = 'c++'
languages[1] = 'python'
languages[2] = 'javascript'
print(languages)
languages.insert(1,'typescript')
languages.append('java')
languages.append('c#')
print(languages)
print(f"If ill add another programming languge, it should be {languages[-1].title()}, {languages[4].title()} and {languages[1].title()}.")
del languages[-1]
print(languages)
languages.pop()
print(languages)
languages.remove('typescript')
print(languages)
print("Thats it, thats all the funtions for this chapter")